namespace: gregheffner
name: ubuntu_patching
version: 1.2.6
readme: README.md

authors:
  - gregheffner

description: Complete Ubuntu system maintenance collection - run all roles together for comprehensive patching, Kubernetes cluster maintenance, and automated infrastructure updates

license:
  - MIT

tags:
  - ubuntu
  - maintenance
  - patching
  - kubernetes
  - system
  - monitoring
  - datadog
  - updates
  - security
  - automation
  - infrastructure
  - complete
  - comprehensive

dependencies: {}

repository: https://github.com/gregheffner/ansible-collection-ubuntu-patching
documentation: https://github.com/gregheffner/ansible-collection-ubuntu-patching
homepage: https://github.com/gregheffner/ansible-collection-ubuntu-patching
issues: https://github.com/gregheffner/ansible-collection-ubuntu-patching/issues

build_ignore:
  - '*.tar.gz'
  - '.git'
  - '.gitignore'
  - 'tests/'
  - '**/*.pyc'
  - '**/*.retry'
