---
# Task-Level Targeting - More granular control
- name: Granular Host Targeting
  hosts: all
  become: true
  serial: 1
  gather_facts: true
  
  vars:
    perform_reboot: true
    update_docker: true
    pause_monitors_enabled: true
    
  tasks:
    # Run K8s maintenance only on K8s cluster nodes
    - name: Run K8s maintenance on cluster nodes
      include_role:
        name: gregheffner.ubuntu_patching.k8_maintenance
      when: 
        - "'k8s_cluster' in group_names"
        - "ansible_distribution == 'Ubuntu'"
      tags: ['k8s_maintenance']
    
    # Run Ubuntu update on all Ubuntu systems
    - name: Run Ubuntu updates on all Ubuntu hosts
      include_role:
        name: gregheffner.ubuntu_patching.ubuntu_update
      when: "ansible_distribution == 'Ubuntu'"
      tags: ['ubuntu_update']
    
    # Custom tasks for specific host groups
    - name: Additional tasks for web servers
      debug:
        msg: "Running additional web server tasks"
      when: "'web_servers' in group_names"
      
    - name: Additional tasks for database servers  
      debug:
        msg: "Running additional database server tasks"
      when: "'database_servers' in group_names"