---
# Simple cron-friendly maintenance playbook
# Add to crontab: 0 6 * * 6 cd /path/to/collection && ansible-playbook maintenance-cron.yml
- name: Weekly Infrastructure Maintenance (Cron Version)
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Log maintenance start
      lineinfile:
        path: /mnt/QNAP/backuplogs/ansible-automation.log
        line: "[{{ ansible_date_time.iso8601 }}] === CRON MAINTENANCE START ==="
        create: yes

    - name: Run K8s cluster maintenance
      include_role:
        name: gregheffner.ubuntu_patching.k8_maintenance
      vars:
        pause_monitors_enabled: true
        k8s_skip_tls_verify: true
      delegate_to: "{{ item }}"
      loop: "{{ groups['k8s_cluster'] }}"
      serial: 1

    - name: Run Docker host maintenance  
      include_role:
        name: gregheffner.ubuntu_patching.ubuntu_update
      vars:
        reboot_enabled: true
      delegate_to: "{{ item }}"
      loop: "{{ groups['dockerhost'] }}"

    - name: Log maintenance completion
      lineinfile:
        path: /mnt/QNAP/backuplogs/ansible-automation.log
        line: "[{{ ansible_date_time.iso8601 }}] === CRON MAINTENANCE COMPLETE ==="