---
# Smart All-Roles Playbook - Automatic role targeting based on host groups
# This is the recommended playbook for complete infrastructure maintenance

- name: Run All Roles from ubuntu_patching Collection (Smart Conditional)
  hosts: all
  become: true
  serial: 1  # For safety, especially with K8s nodes
  gather_facts: true
  
  vars:
    # === Common variables for all roles ===
    perform_reboot: true
    update_docker: true
    pause_monitors_enabled: true
    
    # === K8s-specific variables ===
    pause_duration: 3600  # 1 hour
    k8_primary_node: "{{ groups['k8s_cluster'][0] if 'k8s_cluster' in groups else inventory_hostname }}"
    reboot_delay: 30
    k8s_reboot_timeout: 600
    node_ready_retries: 30
    node_ready_delay: 10
    update_log_path: "/tmp/maintenance.log"
    
    # === Ubuntu update variables ===
    perform_dist_upgrade: false  # Conservative for automation
    cleanup_packages: true
    reboot_method: "modern"
    reboot_timeout: 600
    connect_timeout: 20

  pre_tasks:
    - name: Display smart targeting information
      debug:
        msg: |
          Smart Targeting Active:
          - Host: {{ inventory_hostname }}
          - Groups: {{ group_names }}
          - K8s Maintenance: {{ 'YES' if 'k8s_cluster' in group_names else 'NO' }}
          - Ubuntu Update: {{ 'YES' if 'docker' in group_names else 'NO' }}

  roles:
    # K8s maintenance runs FIRST and only on K8s cluster hosts
    - role: gregheffner.ubuntu_patching.k8_maintenance
      tags: ['k8s_maintenance', 'kubernetes']
      when: "'k8s_cluster' in group_names"
      
    # Ubuntu update runs LAST on docker hosts only
    - role: gregheffner.ubuntu_patching.ubuntu_update
      tags: ['ubuntu_update', 'system_packages']
      when: "'docker' in group_names"

  post_tasks:
    - name: Display completion status
      debug:
        msg: |
          Smart All-Roles Maintenance Completed:
          - Host: {{ inventory_hostname }}
          - K8s Maintenance: {{ 'EXECUTED' if 'k8s_cluster' in group_names else 'SKIPPED' }}
          - Ubuntu Update: {{ 'EXECUTED' if 'docker' in group_names else 'SKIPPED' }}
          - Time: {{ ansible_date_time.iso8601 }}