---
# test_all_roles.yml - Test playbook for gregheffner.ubuntu_patching collection
# This playbook demonstrates running all collection roles with comprehensive testing

- name: Test All Roles from ubuntu_patching Collection
  hosts: all
  become: true
  serial: 1  # For safety, especially with K8s nodes
  gather_facts: true
  
  vars:
    # === Test Configuration ===
    test_mode: true  # Set to false for actual maintenance
    
    # === K8s Maintenance Role Variables ===
    # Datadog monitoring settings
    pause_monitors_enabled: true
    pause_duration: 1800  # 30 minutes for testing
    
    # Kubernetes settings
    k8_primary_node: "{{ groups['k8s_cluster'][0] if 'k8s_cluster' in groups else inventory_hostname }}"
    reboot_delay: 30
    k8s_reboot_timeout: 600  # Renamed to avoid conflict
    node_ready_retries: 30
    node_ready_delay: 10
    
    # Logging settings
    update_log_path: "/tmp/test_maintenance.log"
    
    # === Ubuntu Update Role Variables ===
    # Docker settings
    update_docker: true
    restart_docker_containers: true
    
    # Package update settings
    update_packages: true
    update_apt_packages: true
    perform_dist_upgrade: false  # Conservative for testing
    cleanup_packages: true
    
    # Reboot settings
    perform_reboot: "{{ not test_mode }}"  # Only reboot if not in test mode
    force_reboot: false
    reboot_method: "modern"
    reboot_timeout: 600
    connect_timeout: 20

  pre_tasks:
    - name: Display test start information
      debug:
        msg: |
          ===============================================
          Starting Collection Test on: {{ inventory_hostname }}
          Test Mode: {{ test_mode }}
          Host Groups: {{ group_names }}
          Time: {{ ansible_date_time.iso8601 }}
          ===============================================
    
    - name: Verify system compatibility
      fail:
        msg: "This collection only supports Ubuntu systems"
      when: ansible_distribution != "Ubuntu"
      
    - name: Display system information
      debug:
        msg: |
          System: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Architecture: {{ ansible_architecture }}
          Kernel: {{ ansible_kernel }}
          Memory: {{ ansible_memtotal_mb }}MB
          CPU Cores: {{ ansible_processor_vcpus }}
    
    - name: Check if this is a K8s node
      debug:
        msg: "This host {{ 'IS' if 'k8s_cluster' in group_names else 'IS NOT' }} part of k8s_cluster group"
    
    - name: Check Docker status (if applicable)
      shell: docker --version
      register: docker_version
      changed_when: false
      failed_when: false
      
    - name: Display Docker information
      debug:
        msg: "Docker: {{ docker_version.stdout if docker_version.rc == 0 else 'Not installed or not accessible' }}"
    
    - name: Check kubectl access (for K8s nodes)
      shell: kubectl version --client --short
      register: kubectl_version
      changed_when: false
      failed_when: false
      when: "'k8s_cluster' in group_names"
      
    - name: Display kubectl information
      debug:
        msg: "Kubectl: {{ kubectl_version.stdout if kubectl_version.rc == 0 else 'Not accessible' }}"
      when: "'k8s_cluster' in group_names"
    
    - name: Create test log entry
      lineinfile:
        path: "{{ update_log_path }}"
        line: "{{ ansible_date_time.iso8601 }} - [TEST START] {{ inventory_hostname }} - Test Mode: {{ test_mode }}"
        create: true
      delegate_to: localhost

  roles:
    # IMPORTANT: K8s maintenance runs FIRST to prevent interruption
    - role: gregheffner.ubuntu_patching.k8_maintenance
      tags: ['k8s_maintenance', 'kubernetes', 'test_k8s']
      when: "'k8s_cluster' in group_names"
      
    # Ubuntu update runs LAST and only on docker hosts
    - role: gregheffner.ubuntu_patching.ubuntu_update
      tags: ['ubuntu_update', 'system_packages', 'test_ubuntu']
      when: "'docker' in group_names"

  post_tasks:
    - name: Verify system responsiveness
      ping:
      
    - name: Check for failed services
      shell: systemctl --failed --no-pager
      register: failed_services
      changed_when: false
      failed_when: false
      
    - name: Report any failed services
      debug:
        msg: "{{ 'No failed services' if failed_services.stdout | length == 0 else 'FAILED SERVICES: ' + failed_services.stdout }}"
      
    - name: Check system uptime
      setup:
        filter: ansible_uptime_seconds
      
    - name: Display uptime information
      debug:
        msg: "System uptime: {{ (ansible_uptime_seconds / 3600) | round(2) }} hours"
    
    - name: Verify Docker containers (if applicable)
      shell: docker ps --format "table {{.Names}}\t{{.Status}}"
      register: docker_containers
      changed_when: false
      failed_when: false
      when: update_docker | default(false)
      
    - name: Display Docker container status
      debug:
        msg: |
          Docker Containers:
          {{ docker_containers.stdout }}
      when: update_docker | default(false) and docker_containers.rc == 0
    
    - name: Check K8s node status (for K8s nodes)
      shell: kubectl get node {{ inventory_hostname }} -o wide
      register: k8s_node_status
      changed_when: false
      failed_when: false
      when: "'k8s_cluster' in group_names"
      
    - name: Display K8s node status
      debug:
        msg: |
          Kubernetes Node Status:
          {{ k8s_node_status.stdout }}
      when: "'k8s_cluster' in group_names and k8s_node_status.rc == 0"
    
    - name: Display test completion summary
      debug:
        msg: |
          ===============================================
          COLLECTION TEST COMPLETED SUCCESSFULLY
          Host: {{ inventory_hostname }}
          Completed: {{ ansible_date_time.iso8601 }}
          Roles Executed:
          {{ '- k8_maintenance (K8s node)' if 'k8s_cluster' in group_names else '' }}
          - ubuntu_update
          Test Mode: {{ test_mode }}
          ===============================================
    
    - name: Log test completion
      lineinfile:
        path: "{{ update_log_path }}"
        line: "{{ ansible_date_time.iso8601 }} - [TEST COMPLETE] {{ inventory_hostname }} - SUCCESS"
      delegate_to: localhost

  handlers:
    - name: Display handler execution
      debug:
        msg: "Handler triggered on {{ inventory_hostname }}"