on:
  workflow_dispatch:
  workflow_call:
    secrets:
      KUBECONFIG:
        required: true

jobs:
  delete-pods:
    runs-on: self-hosted
    env:
      KUBECONFIG: ${{ github.workspace }}/kubeconfig
    steps:
      - name: Check last weekly-maintenance run status
        id: check_status
        env:
          GITHUB_TOKEN: ${{ secrets.MY_API_KEY }}
        run: |
          STATUS=$(gh run list --workflow=weekly-maintenance.yml --limit=1 --json conclusion -q '.[0].conclusion')
          if [ "$STATUS" != "success" ]; then
            echo "Last weekly-maintenance.yml run was not successful. Exiting."
            exit 1
          fi

      - name: Configure Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > kubeconfig

      - name: Delete pods in all namespaces
        run: |
          kubectl get ns -o jsonpath='{.items[*].metadata.name}' | xargs -n1 -I{} kubectl delete pods --all -n {}
